# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 14:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('details', models.TextField()),
                ('number_of_bedrooms', models.IntegerField(max_length=60)),
                ('bedrooms_size', models.IntegerField(max_length=60)),
                ('number_of_washrooms', models.IntegerField(max_length=60)),
                ('washroom_size', models.IntegerField(max_length=60)),
                ('total_size', models.IntegerField(max_length=60)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('file_1', models.FileField(blank=True, upload_to='files/')),
                ('file_2', models.FileField(blank=True, upload_to='files/')),
                ('file_3', models.FileField(blank=True, upload_to='files/')),
                ('file_4', models.FileField(blank=True, upload_to='files/')),
                ('file_5', models.FileField(blank=True, upload_to='files/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
