# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_designs_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='designs',
            name='date_of_completion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='designs',
            name='floor_area',
            field=models.IntegerField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='designs',
            name='house_type',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='designs',
            name='kitchen_size',
            field=models.IntegerField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='designs',
            name='land_location',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='designs',
            name='living_room_size',
            field=models.IntegerField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='designs',
            name='master_bedroom_size',
            field=models.IntegerField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='designs',
            name='number_of_windows',
            field=models.IntegerField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='designs',
            name='roofing_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='designs',
            name='ventilation_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='designs',
            name='wall_material',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='designs',
            name='bedrooms_size',
            field=models.IntegerField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='designs',
            name='number_of_bedrooms',
            field=models.IntegerField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='designs',
            name='number_of_washrooms',
            field=models.IntegerField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='designs',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='designs',
            name='washroom_size',
            field=models.IntegerField(max_length=60, null=True),
        ),
    ]
