# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0004_auto_20181024_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='designs',
            name='product',
            field=models.FileField(default='Will be uploaded', upload_to='files/'),
        ),
    ]
