# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0006_auto_20181025_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designs',
            name='cost',
            field=models.CharField(default='Design under review', max_length=60),
        ),
    ]
