# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0008_auto_20181025_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designs',
            name='cost',
            field=models.IntegerField(max_length=60, null=True),
        ),
    ]
